var searchData=
[
  ['i_20chose_20it_0',['Why I chose it',['../md_uml_2extra_2lab1d-uml-tool-report_2UML__TOOL__REPORT.html#autotoc_md100',1,'']]],
  ['i_20used_1',['Supported diagrams I used',['../md_uml_2extra_2lab1d-uml-tool-report_2UML__TOOL__REPORT.html#autotoc_md101',1,'']]],
  ['implementation_20details_2',['Technical Implementation Details',['../md_docs_2documentation__en.html#autotoc_md20',1,'']]],
  ['in_20battle_3',['In battle',['../md_README.html#autotoc_md81',1,'']]],
  ['in_20diagrams_4',['UML notation used in diagrams',['../md_GLOSSARY.html#autotoc_md71',1,'']]],
  ['in_20game_5',['In game',['../md_README.html#autotoc_md80',1,'']]],
  ['info_6',['info',['../classLogger.html#ab4c4d86279176eb0ede726bc5b4d5ddb',1,'Logger']]],
  ['inheritance_20hierarchy_7',['Inheritance Hierarchy',['../md_README.html#autotoc_md94',1,'']]],
  ['instagram_20glossary_8',['Instagram Glossary',['../md_uml_2extra_2lab1b-instagram_2GLOSSARY.html',1,'']]],
  ['interface_9',['Command Interface',['../md_docs_2mechanics__en.html#autotoc_md59',1,'']]],
  ['inventory_10',['inventory',['../classCharacter.html#a4b781b13dfc99a1e8758ca25d6144f30',1,'Character::inventory'],['../md_GLOSSARY.html#autotoc_md69',1,'Items / Inventory']]],
  ['inventory_20management_11',['Inventory Management',['../md_docs_2documentation__en.html#autotoc_md19',1,'']]],
  ['isalive_12',['isAlive',['../classCharacter.html#aced814c6549d4243897ab976d243bd5c',1,'Character']]],
  ['it_13',['Why I chose it',['../md_uml_2extra_2lab1d-uml-tool-report_2UML__TOOL__REPORT.html#autotoc_md100',1,'']]],
  ['item_14',['item',['../classItem.html#a26916bef9e0a1f842e3521a16b7a4f6b',1,'Item::Item()'],['../classItem.html',1,'Item']]],
  ['item_20базовий_20клас_15',['Item (Базовий клас)',['../md_docs_2documentation__ua.html#autotoc_md43',1,'']]],
  ['item_20base_20class_16',['Item (Base Class)',['../md_docs_2documentation__en.html#autotoc_md14',1,'']]],
  ['item_20system_17',['Item System',['../md_docs_2documentation__en.html#autotoc_md13',1,'']]],
  ['item_2eh_18',['Item.h',['../Item_8h.html',1,'']]],
  ['item_5fexample_2ecpp_19',['item_example.cpp',['../item__example_8cpp.html',1,'']]],
  ['items_20inventory_20',['Items / Inventory',['../md_GLOSSARY.html#autotoc_md69',1,'']]],
  ['itemstests_2ecpp_21',['ItemsTests.cpp',['../ItemsTests_8cpp.html',1,'']]]
];
