var searchData=
[
  ['chance_0',['chance',['../classUtils.html#a34d71e3b887e382414b41f87de251427',1,'Utils']]],
  ['character_1',['character',['../classCharacter.html#a741517cba17f9eb8cefcce81237839fe',1,'Character::Character()'],['../classCharacter.html',1,'Character']]],
  ['character_20базовий_20клас_2',['Character (Базовий клас)',['../md_docs_2documentation__ua.html#autotoc_md39',1,'']]],
  ['character_20base_20class_3',['Character (Base Class)',['../md_docs_2documentation__en.html#autotoc_md10',1,'']]],
  ['character_20class_4',['Character Class',['../md_README.html#autotoc_md88',1,'']]],
  ['character_2ecpp_5',['Character.cpp',['../Character_8cpp.html',1,'']]],
  ['character_2eh_6',['Character.h',['../Character_8h.html',1,'']]],
  ['character_5fexample_2ecpp_7',['character_example.cpp',['../character__example_8cpp.html',1,'']]],
  ['characters_8',['Entities / Characters',['../md_GLOSSARY.html#autotoc_md67',1,'']]],
  ['class_9',['class',['../md_docs_2documentation__en.html#autotoc_md10',1,'Character (Base Class)'],['../md_README.html#autotoc_md88',1,'Character Class'],['../md_README.html#autotoc_md90',1,'Enemy Class'],['../md_docs_2documentation__en.html#autotoc_md5',1,'Game Class'],['../md_README.html#autotoc_md87',1,'Game Class'],['../md_docs_2documentation__en.html#autotoc_md14',1,'Item (Base Class)'],['../md_README.html#autotoc_md91',1,'LocationNode Class'],['../md_README.html#autotoc_md89',1,'Player Class'],['../md_README.html#autotoc_md93',1,'Weapon Class'],['../md_README.html#autotoc_md92',1,'WorldMap Class']]],
  ['classes_20and_20their_20fields_10',['Classes and Their Fields',['../md_README.html#autotoc_md85',1,'']]],
  ['clearline_11',['clearLine',['../classUtils.html#a454d8fa57017db4808eea2e90b1b3f59',1,'Utils']]],
  ['code_20analysis_12',['Code Analysis',['../md_README.html#autotoc_md84',1,'']]],
  ['codebase_20structure_20summary_13',['Codebase Structure Summary',['../md_README.html#autotoc_md95',1,'']]],
  ['combat_14',['Combat',['../md_GLOSSARY.html#autotoc_md68',1,'']]],
  ['combat_20system_15',['combat system',['../md_docs_2mechanics__en.html#autotoc_md60',1,'Combat System'],['../md_docs_2documentation__en.html#autotoc_md17',1,'Combat System']]],
  ['combatlog_16',['combatLog',['../classLogger.html#a81ead3e546938be3daa7b9553f854eae',1,'Logger']]],
  ['command_20interface_17',['Command Interface',['../md_docs_2mechanics__en.html#autotoc_md59',1,'']]],
  ['common_20technical_18',['Common / Technical',['../md_GLOSSARY.html#autotoc_md70',1,'']]],
  ['component_20documentation_19',['Detailed Component Documentation',['../md_docs_2documentation__en.html#autotoc_md4',1,'']]],
  ['components_20',['Main Components',['../md_docs_2documentation__en.html#autotoc_md3',1,'']]],
  ['considerations_21',['Performance Considerations',['../md_docs_2documentation__en.html#autotoc_md26',1,'']]],
  ['controls_22',['Controls',['../md_README.html#autotoc_md79',1,'']]],
  ['core_20architecture_23',['Core Architecture',['../md_docs_2documentation__en.html#autotoc_md2',1,'']]],
  ['core_20game_20flow_24',['Core / Game flow',['../md_GLOSSARY.html#autotoc_md65',1,'']]]
];
